apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: frontend-ns
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flaskapi
    type: LoadBalancer
#  type: NodePort
