apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flaskapi-deployment-hpa
  namespace: frontend-ns
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapi-deployment
  targetCPUUtilizationPercentage: 30