---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  namespace: frontend-ns
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: ritikgupta/movie
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: db_name
              value: flaskapi
            - name: MYSQL_SERVICE_HOST
              value: mysql.backend-ns.svc.cluster.local
            - name: MYSQL_DATABASE_PORT
              value: "3306"
          resources:
            requests:
              memory: "500Ki"
              cpu: "250m"
              ephemeral-storage: "2Mi"
            limits:
              memory: "100Mi"
              cpu: "500m"
              ephemeral-storage: "20Mi"

