apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: backend-ns
  labels:
    app: db
spec:
  clusterIP: None 
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: ClusterIP